# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxContacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxContacts
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'SnapKit', '5.0.1'
  pod 'ReactorKit'
end
